[project]
name = "9-18-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "KyUuuzzz", email = "d1546657@o365.fcu.edu.tw" }
]
requires-python = ">=3.12.10"
dependencies = []

[project.scripts]
9-18-python = "9_18_python:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
